# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_field', models.CharField(blank=True, max_length=30, null=True)),
                ('password_field', models.CharField(blank=True, max_length=30, null=True)),
                ('is_admin', models.BinaryField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.Employees')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
