# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-06 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='login_field',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password_field',
            new_name='password',
        ),
    ]
